import Navbar from "@/app/components/Navbar/Navbar";
import "./styles/global.scss";

import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Hydrate from "@/app/components/Hydrate/Hydrate";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <Hydrate>
        {/* @ts-ignore */}
        <Navbar user={session?.user} />
        {children}
      </Hydrate>
    </html>
  );
}
